GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/persons/3

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "DDQuin",
  "url": "http://google.com",
  "likes": 5
}

###
GET http://localhost:3001/info

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
GET http://localhost:3003/api/users